### ISSUE TITLE
how to integrate orocrm and magento2?

### ISSUE THREAD

**Issue by woei66** [oroinc/crm#148]
hi, folks,

does anyone know how to integrate orocrm and magento2?
I didn't see any orocrm extension for magento2.
if you know how to integrate both, please kindly let me know.
thank you.

**Comment by DimaSoroka** [comment]
We do not support Magento 2 yet, extension update is on our roadmap.

**Comment by woei66** [comment]
I didn't see magento2 support are put in http://www.orocrm.com/orocrm-and-platform-roadmap
Do you have the ETA of magento2 support?
Or you can share any suggestion to us and maybe we can help to create a branch to support magento2 with community support?

**Comment by DimaSoroka** [comment]
We planned this for Q2/Q3 this year.

**Comment by woei66** [comment]
good and thank you.

**Comment by pitbulk** [comment]
I recommend to use SAML in order to integrate accounts as suggested here:
https://www.orocrm.com/forums/topic/how-to-integrate-orocrm-and-magento2#post-21811

This will solve SSO, SLO and user provisioning.

Once authenticated, you can use the [Magento2 API](http://devdocs.magento.com/guides/v2.0/rest/list.html)

**Comment by cdbessig** [comment]
@DimaSoroka any update on timeline for this?

**Comment by DimaSoroka** [comment]
Sorry for late update, after backlog update we removed Magento 2 integration from our roadmap, feel free to implement it as extension and add to our marketplace.
