### ISSUE TITLE
`oro_html_filter` doesnt exists

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#176]
Hi Oro Tearm,

When creating an html template,
![image](https://cloud.githubusercontent.com/assets/794449/15661651/9363b72c-26b7-11e6-8aa5-c33f038d4e8c.png)

But the `oro_html_filter`doesnt exist
![image](https://cloud.githubusercontent.com/assets/794449/15661682/d828386a-26b7-11e6-9277-e834a21a4238.png)

**Comment by artml** [comment]
@sadortun thanks for the bug report. We are aware of this issue, but it's hard to tell how quickly it will be fixed (and I can't promise it fixed in 1.10 according to our current priorities).

I'm marking this as open for contribution for now, so if you or anyone else is willing to contribute the fix—you're welcome.
