### ISSUE TITLE
OroCalandar  2.3 broken

### ISSUE THREAD

**Issue by sadortun** [oroinc/crm#305]
Orocalandar 2.3.7  need `AuditAdditionalFieldsInterface`  defined in `oro/platform` but  the class is not available for the 2.3 branch.

```
  [Symfony\Component\Debug\Exception\ClassNotFoundException]
  Attempted to load interface "AuditAdditionalFieldsInterface" from namespace "Oro\Bundle\DataAuditBundle\Entity".
  Did you forget a "use" statement for another namespace?

```

**Comment by Briones** [comment]
I'm trying to update from a 2.3 version of OroCRM to a 2.3.12, so I'm running:

`composer update oro/platform-serialised-fields oro/crm-hangouts-call-bundle oro/crm --with-dependencies`

But I get the same error, If OroCalendar is version 2.3.7 should be compatible with the 2.3.* versions of the other packages, but is not, @mbessolov you say that the latest stable release for that bundle is the 2.6.2 at the moment of your comment, but that will imply to update to OroCRM / Platform to 2.6.0 instead of just the security fixes of 2.3.* ... That doesn't make any sense to me.

**Comment by mbessolov** [comment]
Well, as it is explained in the documentation here - https://oroinc.com/orocrm/doc/current/community/release-process#orocrm-community-edition-releases, we had supported 2.3 LTS version of OroCRM Community Edition only until version 2.6 LTS was released.

If you want to keep receiving security fixes for Community Edition of OroCRM - you should upgrade to 2.6 LTS.

**Comment by Briones** [comment]
Yeah, I know, I'm waiting for it, but the thing is for the moment I just want to update to 2.3.12 that is the latest release of the 2.3 versions. And the problem here is that since the  2.3.3 package of OroCalendar:

https://github.com/oroinc/OroCalendarBundle/releases/tag/2.3.3

That has a composer.json that requires an "oro/platform": "2.3.*" it uses a file that is not been added until a 2.5 version of oro platform:

https://github.com/oroinc/platform/commit/e0c36af9d042cb0365bdf12a6e4f189a9127013e

That's the part that doesn't make any sense to me. I wanted to update to a 3 / 3.1 version, even to a 2.6 but I getting different errors when I tried so I'm waiting fot the 3.1 but for the moment just want to update from a 2.3 to a 2.3.12, that kind of update should be very transparent and possible, otherwise why keeping that releases in the repository? 

Thanks for the reply also.
